### ISSUE TITLE
build error on mac osx

### ISSUE THREAD

**Issue by yingnierxiao** [satoren/LRDB#1]
[100%] Linking CXX shared library lrdb_server.dylib
Undefined symbols for architecture x86_64:
  "_luaL_callmeta", referenced from:
      lrdb::utility::to_json(lua_State*, int, int) in debug_server_module.cpp.o
  "_luaL_getmetafield", referenced from:
      lrdb::utility::to_json(lua_State*, int, int) in debug_server_module.cpp.o
  "_luaL_loadstring", referenced from:
      lrdb::debug_info::eval(char const*, bool, bool, bool, int) in debug_server_module.cpp.o
  "_lua_absindex", referenced from:
      lrdb::utility::to_json(lua_State*, int, int) in debug_server_module.cpp.o
  "_lua_createtable", referenced from:
      _luaopen_lrdb_server in debug_server_module.cpp.o
      lrdb::debug_info::create_eval_env(bool, bool, bool) in debug_server_module.cpp.o
  "_lua_getinfo", referenced from:
      lrdb::debug_info::get_info(char const*) in debug_server_module.cpp.o
      lrdb::debug_info::create_eval_env(bool, bool, bool) in debug_server_module.cpp.o
      lrdb::debug_info::get_upvalues(int) in debug_server_module.cpp.o
  "_lua_getlocal", referenced from:
      lrdb::debug_info::create_eval_env(bool, bool, bool) in debug_server_module.cpp.o
      lrdb::debug_info::get_local_vars(int) in debug_server_module.cpp.o
  "_lua_getstack", referenced from:
      lrdb::stack_info::stack_info(lua_State*, int) in debug_server_module.cpp.o
  "_lua_gettop", referenced from:
      _luaopen_lrdb_server in debug_server_module.cpp.o
      lrdb::debug_info::eval(char const*, bool, bool, bool, int) in debug_server_module.cpp.o
      lrdb::debug_info::create_eval_env(bool, bool, bool) in debug_server_module.cpp.o
  "_lua_getupvalue", referenced from:
      lrdb::debug_info::create_eval_env(bool, bool, bool) in debug_server_module.cpp.o
      lrdb::debug_info::get_upvalues(int) in debug_server_module.cpp.o
  "_lua_isnumber", referenced from:
      lrdb_activate(lua_State*) in debug_server_module.cpp.o
  "_lua_newuserdata", referenced from:
      _luaopen_lrdb_server in debug_server_module.cpp.o
  "_lua_next", referenced from:
      lrdb::utility::to_json(lua_State*, int, int) in debug_server_module.cpp.o
  "_lua_pcallk", referenced from:
      lrdb::debug_info::eval(char const*, bool, bool, bool, int) in debug_server_module.cpp.o
  "_lua_pushcclosure", referenced from:
      _luaopen_lrdb_server in debug_server_module.cpp.o
  "_lua_pushlightuserdata", referenced from:
      lrdb::debugger::unsethook() in debug_server_module.cpp.o
      lrdb::debugger::sethook() in debug_server_module.cpp.o
  "_lua_pushnil", referenced from:
      lrdb::debugger::unsethook() in debug_server_module.cpp.o
      lrdb::utility::to_json(lua_State*, int, int) in debug_server_module.cpp.o
  "_lua_pushvalue", referenced from:
      _luaopen_lrdb_server in debug_server_module.cpp.o
      lrdb::debug_info::create_eval_env(bool, bool, bool) in debug_server_module.cpp.o
  "_lua_rawgeti", referenced from:
      lrdb::debug_info::create_eval_env(bool, bool, bool) in debug_server_module.cpp.o
      lrdb::debugger::get_global_table(int) in debug_server_module.cpp.o
  "_lua_rawgetp", referenced from:
      lrdb::debugger::hook_function(lua_State*, lua_Debug*) in debug_server_module.cpp.o
  "_lua_rawlen", referenced from:
      lrdb::utility::to_json(lua_State*, int, int) in debug_server_module.cpp.o
  "_lua_rawset", referenced from:
      lrdb::debugger::unsethook() in debug_server_module.cpp.o
      lrdb::debugger::sethook() in debug_server_module.cpp.o
  "_lua_rawseti", referenced from:
      lrdb::debug_info::create_eval_env(bool, bool, bool) in debug_server_module.cpp.o
  "_lua_setfield", referenced from:
      _luaopen_lrdb_server in debug_server_module.cpp.o
      lrdb::debug_info::create_eval_env(bool, bool, bool) in debug_server_module.cpp.o
  "_lua_sethook", referenced from:
      lrdb::debugger::unsethook() in debug_server_module.cpp.o
      lrdb::debugger::sethook() in debug_server_module.cpp.o
  "_lua_setmetatable", referenced from:
      _luaopen_lrdb_server in debug_server_module.cpp.o
      lrdb::debug_info::create_eval_env(bool, bool, bool) in debug_server_module.cpp.o
  "_lua_settop", referenced from:
      lrdb::debugger::hook_function(lua_State*, lua_Debug*) in debug_server_module.cpp.o
      lrdb::debug_info::eval(char const*, bool, bool, bool, int) in debug_server_module.cpp.o
      lrdb::debug_info::create_eval_env(bool, bool, bool) in debug_server_module.cpp.o
      lrdb::utility::to_json(lua_State*, int, int) in debug_server_module.cpp.o
      lrdb::debug_info::get_local_vars(int) in debug_server_module.cpp.o
      lrdb::debug_info::get_upvalues(int) in debug_server_module.cpp.o
      lrdb::debugger::get_global_table(int) in debug_server_module.cpp.o
      ...
  "_lua_setupvalue", referenced from:
      lrdb::debug_info::eval(char const*, bool, bool, bool, int) in debug_server_module.cpp.o
  "_lua_toboolean", referenced from:
      lrdb::utility::to_json(lua_State*, int, int) in debug_server_module.cpp.o
  "_lua_tolstring", referenced from:
      lrdb::utility::to_json(lua_State*, int, int) in debug_server_module.cpp.o
  "_lua_tonumberx", referenced from:
      lrdb_activate(lua_State*) in debug_server_module.cpp.o
      lrdb::utility::to_json(lua_State*, int, int) in debug_server_module.cpp.o
  "_lua_topointer", referenced from:
      lrdb::utility::to_json(lua_State*, int, int) in debug_server_module.cpp.o
  "_lua_touserdata", referenced from:
      lrdb_activate(lua_State*) in debug_server_module.cpp.o
      lrdb_deactivate(lua_State*) in debug_server_module.cpp.o
      lrdb_destruct(lua_State*) in debug_server_module.cpp.o
      lrdb::debugger::hook_function(lua_State*, lua_Debug*) in debug_server_module.cpp.o
  "_lua_type", referenced from:
      lrdb::utility::to_json(lua_State*, int, int) in debug_server_module.cpp.o
  "_lua_typename", referenced from:
      lrdb::utility::to_json(lua_State*, int, int) in debug_server_module.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lrdb_server.dylib] Error 1
make[1]: *** [CMakeFiles/lrdb_server.dir/all] Error 2
make: *** [all] Error 2

**Comment by satoren** [comment]
Thank you for report.
