### ISSUE TITLE
why  can't my LRDB debug TCP request in openresty server using lua?

### ISSUE THREAD

**Issue by mzhiyuan** [satoren/LRDB#2]
The breakpoint is unverified, so it won't be stoped. This is my launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lua",
            "request": "attach",
            "name": "Lua Attach",
            "host": "localhost",
            "port": 8080,
            "sourceRoot": "${workspaceRoot}",
            "stopOnEntry": true
        }
    ]
}
My server port is 8080, I want LRDB to listen request to 8080.  Is this  right?

**Comment by satoren** [comment]
Is the stopped at lua program entry?

**Comment by zhaoyuanwen** [comment]
No, it doesn't stop. My nginx server is deployed in  cetos7 system of vmware virture machine.  And I use soapUI to send request from host machine.  LRDB in vscode is already start debugging. But it never stoped to catch a TCP GET request.

**Comment by zhaoyuanwen** [comment]
However, zerobrane works good. So, I edit code in vscode, and debug code in zerobrane. Wait for vscode can debug a TCP request.

**Comment by satoren** [comment]
zerobrane is using MobDebug, LRDB and MobDebug is no protocol compatibility.
How do you start debugging server on lua (or host) program?

https://github.com/satoren/LRDB#embedded-to-your-host-program
https://github.com/satoren/LRDB#lua-module

**Comment by zhaoyuanwen** [comment]
First I add zerobrane libs path to lua_package_path  in nginx.conf  file , my path is "/opt/zbstudio/lualibs/?/?.lua;/opt/zbstudio/lualibs/?.lua;". And I need to add  "/opt/zbstudio/bin/linux/x64/clibs/?.so;" to lua_package_cpath parameter in nginx.conf file.
Then I add "require('mobdebug').start()" to function where I need to debug . 
Last I start debug server in zerobrane by "Project->Start Debugger Server".
Now I can debug when request comes to call that function. What I want is I can do this with LRDB.

**Comment by satoren** [comment]
LRDB has not compatibillity for mobdebug
